#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := PID_ESP32

#EXCLUDE_COMPONENTS := 

#EXTRA_CFLAGS += -O0

include $(IDF_PATH)/make/project.mk

